version: "3"
services:
  # api:
  #   build:
  #     context: ./api
  #   ports:
  #     - 3000:3000
  # app:
  #   build:
  #     context: ./app
  #   ports:
  #     - 8080:8080
  db:
    # depends_on:
    #   - api
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
