version: "3"
services:
  api:
    depends_on:
      - db
    build:
      context: ./api
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://root:123456@db:5432/eteg-exam
    networks:
      - eteg-exam-network
  app:
    build:
      context: ./app
    ports:
      - 5173:5173
    networks:
      - eteg-exam-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: eteg-exam
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB_HOST: localhost
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - eteg-exam-network
networks:
  eteg-exam-network:
    driver: bridge
