version: "3"
services:
  api:
    depends_on:
      - db
    restart: always
    build:
      context: ./api
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://root:123456@db:5432/eteg-exam
  app:
    build:
      context: ./app
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: eteg-exam
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB_HOST: localhost
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
